Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu-focal"
    config.vm.box_url = "file://../images/focal-server-cloudimg-amd64-vagrant.box"

    num_machines = 1
    (1..num_machines).each do |i|
        config.vm.define "vm_ansible_master_#{i}" do |node|
            node.vm.hostname = "vm-ansible-master-#{i}"
            node.vm.network "private_network", ip: "10.0.0.#{10 + i}"

            node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
            node.vm.provision "file", source: "~/.ssh/id_rsa-nopass.pub", destination: "/tmp/id_rsa-nopass.pub"
            node.vm.provision "file", source: "~/.ssh/id_rsa-nopass", destination: "/tmp/id_rsa-nopass"

            node.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/tmp/id_rsa-pass"
            node.vm.provision "shell", inline: <<-SHELL
                sudo useradd -m -s /bin/bash tuz
                echo "tuz:tuz" | sudo chpasswd
                sudo usermod -aG sudo tuz
                echo 'tuz ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/tuz
                sudo chmod 440 /etc/sudoers.d/tuz

                sudo -u tuz mkdir -p /home/tuz/.ssh
                sudo chmod 700 /home/tuz/.ssh
                sudo cp /tmp/id_rsa.pub /home/tuz/.ssh/authorized_keys
                sudo echo "" >> /home/tuz/.ssh/authorized_keys && cat /tmp/id_rsa-nopass.pub >> /home/tuz/.ssh/authorized_keys
                sudo chmod 600 /home/tuz/.ssh/authorized_keys
                sudo cp /tmp/id_rsa-nopass /home/tuz/.ssh/id_rsa
                sudo chmod 600 /home/tuz/.ssh/id_rsa
                sudo cp /tmp/id_rsa-pass /home/tuz/.ssh/id_rsa-pass
                sudo chmod 600 /home/tuz/.ssh/id_rsa-pass
                sudo chown -R tuz:tuz /home/tuz/.ssh

                sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
                sudo sed -i 's/PasswordAuthentication yes/#PasswordAuthentication no/g' /etc/ssh/sshd_config
                sudo sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g' /etc/ssh/sshd_config

                sudo sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords no/g' /etc/ssh/sshd_config
                sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/g' /etc/ssh/sshd_config

                sudo systemctl restart ssh

                sudo apt update
                sudo apt install -y software-properties-common
                sudo apt-add-repository --yes --update ppa:ansible/ansible
                sudo apt install -y ansible
            SHELL

            node.vm.provider "virtualbox" do |vb|
                vb.name = "ansible-master-vm-#{i}_#{SecureRandom.hex(4)}"
                vb.memory = "1024"
                vb.cpus = 1
            end
        end
    end
end